/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConnectSQL;
import DAO.TaiKhoanDAO;
import DTO.TaiKhoan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class CaiDatLaiMK extends javax.swing.JFrame {

    /**
     * Creates new form CaiDatLaiMK
     */
    private ConnectSQL connectSQL;
    public Connection conn = ConnectSQL.getConnection();
    public PreparedStatement ps = null;
    public ResultSet rs = null;
    
    public CaiDatLaiMK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTenHienThi = new javax.swing.JTextField();
        tfTenDangNhap = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnMinimize4 = new javax.swing.JLabel();
        lbThoat5 = new javax.swing.JLabel();
        tfMKCu = new javax.swing.JTextField();
        btnAnMKM = new javax.swing.JLabel();
        btnHienMKM = new javax.swing.JLabel();
        tfMatKhauMoi = new javax.swing.JPasswordField();
        btnAnNLMK = new javax.swing.JLabel();
        btnHienNLMK = new javax.swing.JLabel();
        tfNhapLaiMatKhau = new javax.swing.JPasswordField();
        btnAnMKC = new javax.swing.JLabel();
        btnHienMKC = new javax.swing.JLabel();
        tfMatKhauCu = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Tên đăng nhập:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Mật khẩu cũ:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 210, 102, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Mật khẩu mới");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 257, 102, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tên hiển thị:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 163, 102, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Nhập lại MK:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 102, 29));

        tfTenHienThi.setEnabled(false);
        jPanel1.add(tfTenHienThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 29));

        tfTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(tfTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 115, 230, 30));

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 102, 102));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 113, 44));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(0, 102, 102));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 113, 44));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CÀI ĐẶT LẠI MẬT KHẨU");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 32, 310, 60));

        btnMinimize4.setBackground(new java.awt.Color(49, 139, 130));
        btnMinimize4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/subtract_18px.png"))); // NOI18N
        btnMinimize4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize4MouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 8, -1, 33));

        lbThoat5.setBackground(new java.awt.Color(49, 139, 130));
        lbThoat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Close_18px.png"))); // NOI18N
        lbThoat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThoat5MouseClicked(evt);
            }
        });
        jPanel1.add(lbThoat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 8, -1, 33));

        tfMKCu.setBackground(new java.awt.Color(250, 250, 250));
        tfMKCu.setForeground(new java.awt.Color(250, 250, 250));
        tfMKCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(tfMKCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 56, 17));

        btnAnMKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnMKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/eye_16px.png"))); // NOI18N
        btnAnMKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnMKMMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnMKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 30));

        btnHienMKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHienMKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blind_16px.png"))); // NOI18N
        btnHienMKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienMKMMouseClicked(evt);
            }
        });
        jPanel1.add(btnHienMKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 30));
        jPanel1.add(tfMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 262, 230, 30));

        btnAnNLMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/eye_16px.png"))); // NOI18N
        btnAnNLMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnNLMKMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 30, 30));

        btnHienNLMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHienNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blind_16px.png"))); // NOI18N
        btnHienNLMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienNLMKMouseClicked(evt);
            }
        });
        jPanel1.add(btnHienNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 30, 30));

        tfNhapLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhapLaiMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(tfNhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, 30));

        btnAnMKC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnMKC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/eye_16px.png"))); // NOI18N
        btnAnMKC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnMKCMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnMKC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 30, 30));

        btnHienMKC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHienMKC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blind_16px.png"))); // NOI18N
        btnHienMKC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienMKCMouseClicked(evt);
            }
        });
        jPanel1.add(btnHienMKC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 30, 30));
        jPanel1.add(tfMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 212, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimize4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize4MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimize4MouseClicked

    private void lbThoat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThoat5MouseClicked
        int click=JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình hay không?", "Thông báo", 2);
        if(click==JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_lbThoat5MouseClicked

    private void CapNhatMK(String matKhau, String tenDangNhap){
        try{
            String sql="UPDATE TaiKhoan SET matKhau= ? WHERE tenDangNhap=?";
            ps=conn.prepareStatement(sql);
            ps.setString(1, matKhau);
            ps.setString(2, tenDangNhap);
            ps.executeUpdate(); 
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
            try
            {
                String tenDangNhap = tfTenDangNhap.getText();
                String tenHienThi = tfTenHienThi.getText();
                String matKhau = tfMatKhauCu.getText();
                String matKhauMoi = tfMatKhauMoi.getText();
                String nhapLaiMK = tfNhapLaiMatKhau.getText();
                String mkCu = tfMKCu.getText();
                
                if(mkCu.equals(matKhau)){
                    if (!matKhauMoi.equals(nhapLaiMK))
                    {
                        JOptionPane.showMessageDialog(this,"Mật khẩu nhập lại không đúng!");
                    }
                    else
                    {
                        CapNhatMK(matKhauMoi, tenDangNhap);
                        JOptionPane.showMessageDialog(this,"Cập nhật mật khẩu mới thành công!");
                    }
                }else{
                        JOptionPane.showMessageDialog(this,"Mật khẩu cũ không đúng!");
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int click=JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình hay không?", "Thông báo", 2);
        if(click==JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tfTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenDangNhapActionPerformed
        String sql = "SELECT tenHienThi, matKhau FROM TaiKhoan WHERE tenDangNhap = ?";
        try{
            String tenDangNhap = (String) tfTenDangNhap.getText();
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, tenDangNhap);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()){
                tfTenHienThi.setText(rs.getString("tenHienThi"));
               tfMKCu.setText(rs.getString("matKhau"));
            }
        } catch(Exception e){
                JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfTenDangNhapActionPerformed

    private void btnAnMKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnMKMMouseClicked
        btnAnMKM.setVisible(false);
        btnHienMKM.setVisible(true);
        tfMatKhauMoi.setEchoChar((char)0);        
    }//GEN-LAST:event_btnAnMKMMouseClicked

    private void btnHienMKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienMKMMouseClicked
        btnAnMKM.setVisible(true);
        btnHienMKM.setVisible(false);
        tfMatKhauMoi.setEchoChar('*');
    }//GEN-LAST:event_btnHienMKMMouseClicked

    private void tfNhapLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhapLaiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNhapLaiMatKhauActionPerformed

    private void btnAnMKCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnMKCMouseClicked
        btnAnMKC.setVisible(false);
        btnHienMKC.setVisible(true);
        tfMatKhauCu.setEchoChar((char)0);        
    }//GEN-LAST:event_btnAnMKCMouseClicked

    private void btnHienMKCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienMKCMouseClicked
        btnAnMKC.setVisible(true);
        btnHienMKC.setVisible(false);
        tfMatKhauCu.setEchoChar('*');
    }//GEN-LAST:event_btnHienMKCMouseClicked

    private void btnAnNLMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnNLMKMouseClicked
        btnAnNLMK.setVisible(false);
        btnHienNLMK.setVisible(true);
        tfNhapLaiMatKhau.setEchoChar((char)0);      
    }//GEN-LAST:event_btnAnNLMKMouseClicked

    private void btnHienNLMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienNLMKMouseClicked
        btnAnNLMK.setVisible(true);
        btnHienNLMK.setVisible(false);
        tfNhapLaiMatKhau.setEchoChar('*');
    }//GEN-LAST:event_btnHienNLMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaiDatLaiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnMKC;
    private javax.swing.JLabel btnAnMKM;
    private javax.swing.JLabel btnAnNLMK;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JLabel btnHienMKC;
    private javax.swing.JLabel btnHienMKM;
    private javax.swing.JLabel btnHienNLMK;
    private javax.swing.JLabel btnMinimize4;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbThoat5;
    private javax.swing.JTextField tfMKCu;
    private javax.swing.JPasswordField tfMatKhauCu;
    private javax.swing.JPasswordField tfMatKhauMoi;
    private javax.swing.JPasswordField tfNhapLaiMatKhau;
    public static javax.swing.JTextField tfTenDangNhap;
    public static javax.swing.JTextField tfTenHienThi;
    // End of variables declaration//GEN-END:variables
}
